rm -f *.o
rm -f main
rm -f Makefile
rm -f Makefile.in
rm -f a.out
rm -f AUTHORS
rm -f COPYING
rm -f ChangeLog
rm -f INSTALL
rm -f NEWS
rm -f README
rm -f aclocal.m4
rm -f compile
rm -f config.h.in
rm -f config.log
rm -f config.status
rm -f configure
rm -f configure.scan
rm -f depcomp
rm -f install-sh
rm -f missing
rm -f autoscan.log
rm -rf main.dSYM
rm -rf autom4te.cache
rm -rf .deps