name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: autotools
      run: cd autotools;sh ./make.sh;sh clean.sh;cd ..;
    - name: make
      run: make
    - name: C
      run: cd C;make;make clean;cd ..;
    - name: CPP
      run: cd CPP;make;make clean;
      cd thread;make;make clean;cd ..;
      cd static_link;make;make clean;cd ..;
      cd dynamic_link;make;make clean;cd ..;
      cd 11;make;make clean;cd ..;
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
