name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: sudo apt update;sudo apt install gcc-multilib
    - uses: actions/checkout@v2
    - name: C
      run: |
        cd C;
        cd base;make all;make clean;cd ..;
        cd scope;make all;make clean;cd ..;
        cd socket;make all;make clean;cd ..;
        cd bugcode;make;make clean;cd ..;
    - name: CPP
      run: |
        cd CPP;make;make clean;
        cd thread;make;make clean;cd ..;
        cd dynamic_link;make;make clean;cd ..;
        cd static_link;make;make clean;cd ..;
        cd whatsnew;make;make clean;cd ..;
        cd stl;make;make clean;cd ..;
    - name: Linux
      run: |
        cd Linux;make all;make clean;
        cd ..;
    # Github action is Linux env
    # - name: FreeBSD
    #   run: |
    #     cd FreeBSD;make;make clean;
    #     cd ..;
    - name: autotools
      run: cd autotools;sh ./make.sh;sh clean.sh;cd ..;
    - name: algorithm
      run: cd algorithm/leetcode;make all;make run;make clean;cd ../..;
    # - name: make check
    #   run: make check
    # - name: make distcheck
    #   run: make distcheck
